### ISSUE TITLE
CMD run error

### ISSUE THREAD

**Issue by BardofSilence** [Amenly/LoyalFans#1]
I'm using WIN10 x64, and came across an issue where the program fails to run. Attempting to run the program throws an error that states: "ModuleNotFoundError: No module named 'fcntl". 

File "C:\Users\**\LoyalFans-main\loyalfans.py", line 8, in <module>
    from blessings import Terminal
  File "C:\Users\**\AppData\Local\Programs\Python\Python39\lib\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ModuleNotFoundError: No module named 'fcntl'

I'm at a loss on how to fix this, if at all possible.
So, I'm hoping you can find a solution to this, and thank you for your time and help.

**Comment by Amenly** [comment]
Ah, that's unfortunate. I hadn't tested this on Windows. It seems one of the libraries that's responsible for colored text is throwing an error for Windows machines.

Luckily, it seems there's a newer and improved fork of the `blessings` library so I'll see if I can quickly transition the script to that. Otherwise, I'll have to remove it entirely from the script. Give me some time.

**Comment by Amenly** [comment]
Install the `blessed` library by running `pip install blessed` and then try using the latest version. Let me know if you encounter any errors.

**Comment by BardofSilence** [comment]
Hey, just wanted to say it's been functioning fine since the library change. Thank you very much for the help!
